---
version: '3.7'

services:
  mysql:
    image: mysql:8
    restart: always
    ports:
      - "33357:3306"
    environment:
      - MYSQL_DATABASE=trivydb
      - MYSQL_ROOT_PASSWORD=mypass
  postgres:
    image: postgres:10
    restart: always
    ports:
      - "35432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pgpass
      - POSTGRES_DB=trivydb
